---
# tasks file for vim

- name: install vim
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - vim
  tags:
    - vim

- name: vimrc
  copy: src=vimrc dest="/etc/vim/vimrc"
  tags:
    - vim
    - vimrc
 
- name: vundle
  git: 
    repo: https://github.com/gmarik/Vundle.vim.git 
    dest: "{{ home_dir }}/.vim/bundle/Vundle.vim"
  become_user: "{{ become_user }}"
  tags:
    - vim
    - vimrc

- name: install vundle plugins
  shell: vim +PluginInstall +qall
  become_user: "{{ become_user }}"
  tags:
    - vim
    - vimrc

